#!/bin/bash
set -e

if [[ "$#" == 0 || "$1" == "--help" ]]; then
    echo 'Creates a request bundle file (a .zip file). If given, the files'
    echo 'FILE1, FILE2, etc. will be added to the created bundle. Those files'
    echo 'may contain additional information about your Swaptacular node.'
    echo
    echo 'Usage: create-reqbundle BUNDLE_FILENAME[.zip] [FILE1 FILE2 ...]'
    exit 2
fi

function find_script_dir {
    SOURCE=${BASH_SOURCE[0]}
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is not a symlink
        DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
        SOURCE=$(readlink "$SOURCE")
        # If $SOURCE was a relative symlink, we need to resolve it relative
        # to the path where the symlink file was located.
        [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
    done
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
}

find_script_dir || exit 3

if [ ! -s "$DIR/root-ca.csr" ]; then
    echo 'To be able to set up permanent authenticated connections with other'
    echo 'Swaptacular nodes, a certificate signing request (CSR) must be'
    echo 'created first.'
    echo
    openssl req -new \
            -config "$DIR/root-ca.conf" \
            -out "$DIR/root-ca.csr" \
            -key "$DIR/private/root-ca.key" \
            -reqexts ca_official_ext
    openssl req \
            -in "$DIR/root-ca.csr" \
            -text \
            -noout
    echo
fi

servers_file="$DIR/servers.txt"

if [ -s "$servers_file" ]; then
    echo "Found servers.txt file. Reading network addresses from it:"
    cat "$servers_file"
else
    echo 'You must specify the network address of your server(s). The network'
    echo 'address consists of a domain name and a port number, separated by a colon.'
    echo 'For example: "myserver.example.com:1234".'
    echo
    read -p 'Network address: ' server_address
    echo "$server_address" > "$servers_file"
fi

required_files=("$DIR/root-ca.crt" "$DIR/root-ca.csr" "$servers_file")
bundle_file=$(echo "$1" | sed s/\.zip$//).zip
shift

for file in ${required_files[@]} "$@"; do
    if [ ! -f "$file" ]; then
        echo
        echo "ERROR: $file does not exist."
        echo
        exit 1
    fi
done

if [ -s "$bundle_file" ]; then
    echo
    echo "ERROR: $bundle_file already exists."
    echo
    exit 1
fi

zip -Xj "$bundle_file" ${required_files[@]} "$@"

echo
echo '***********************************************************************'
echo '* IMPORTANT: A new request bundle file has been created. If you want  *'
echo '*            to establish a permanent authenticated connection with   *'
echo '*            another Swaptacular node, you should send this file to   *'
echo '*            the owners of the Swaptacular node, and wait for a       *'
echo '*            corresponding response bundle.                           *'
echo '***********************************************************************'
echo "File location: $bundle_file"
