#!/bin/bash

generate_conf_file() {
    envsubst '$ORGANIZATIONAL_UNIT_NAME $SERIAL_NUMBER' \
             < root-ca.conf.template \
             > root-ca.conf
}

mkdir certs db private 2> /dev/null
chmod 700 private
touch db/index

set -e

if [ ! -s db/serial ]; then
    openssl rand -hex 16  > db/serial
fi

if [ ! -s db/crlnumber ]; then
    echo 1001 > db/crlnumber
fi

if [ ! -s root-ca.conf ]; then
    PS3="Specify the type of your Swaptacular node: "
    select opt in "Creditors agent" "Debtors agent" "Accounting authority"
    do
        case $opt in
            "Creditors agent")
                export ORGANIZATIONAL_UNIT_NAME="Creditors Agents"
                export SERIAL_NUMBER=$(uuidgen)
                generate_conf_file
                break
                ;;
            "Debtors agent")
                export ORGANIZATIONAL_UNIT_NAME="Debtors Agents"
                export SERIAL_NUMBER=$(uuidgen)
                generate_conf_file
                break
                ;;
            "Accounting authority")
                export ORGANIZATIONAL_UNIT_NAME="Accounting Authorities"
                export SERIAL_NUMBER=$(uuidgen)
                generate_conf_file
                break
                ;;
            *)
                echo "Invalid option $REPLY"
                ;;
        esac
    done
fi

if [ ! -s private/root-ca.key -o ! -s root-ca.csr ]; then
    openssl req -new \
            -config root-ca.conf \
            -out root-ca.csr \
            -keyout private/root-ca.key \
            -reqexts ca_ext
fi

if [ ! -s root-ca.crt ]; then
    echo "Creating a self-signed certificate for the root CA..."
    openssl ca -selfsign \
            -config root-ca.conf \
            -in root-ca.csr \
            -out root-ca.crt \
            -extensions ca_ext
fi

if [ -s root-ca.crt ]; then
    echo "Creating official certificate signing request..."
    openssl req -new \
            -config root-ca.conf \
            -out root-ca.csr \
            -key private/root-ca.key \
            -reqexts ca_ext_official
fi
