#!/bin/bash
set -e

CSR="$1"
CRT=$(echo "$CSR" | sed s/\.csr$//).crt

DN=$(openssl req -noout -subject -in "$CSR")
export DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
export DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
export DN_SERIAL_NUMBER=$(echo "$DN" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+')

openssl ca \
    -config root-ca.conf \
    -in "$CSR" \
    -out "$CRT" \
    -extensions sub_ca_ext
