#!/bin/bash

if [[ "$#" != 1 && "$#" != 2 || "$1" == "--help" ]]; then
    echo 'Generates a certificate file from a certificate signing request (CSR)'
    echo 'file. The CSR file should be created by/for your server(s), using'
    echo 'a secret private key. The generated certificate can be used by your'
    echo 'server(s) to establish secure SSL connections with other Swaptacular'
    echo 'servers. See the "generate-serverkey" command.'
    echo
    echo 'Usage: sign-servercert CSR_FILE [DAYS]'
    exit 2
fi

function find_script_dir {
    SOURCE=${BASH_SOURCE[0]}
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is not a symlink
        DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
        SOURCE=$(readlink "$SOURCE")
        # If $SOURCE was a relative symlink, we need to resolve it relative
        # to the path where the symlink file was located.
        [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
    done
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
}

find_script_dir || exit 3

csr_file="$1"
crt_file=$(echo "$csr_file" | sed s/\.csr$//).crt

if [ -s "$crt_file" ]; then
    echo
    echo "ERROR: $crt_file file already exists."
    echo
    exit 1
fi

DN=$(openssl req -noout -subject -in "$csr_file")
DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
DN_SERIAL_NUMBER=$(echo "$DN" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+')

set -e

if [[ "$DN_O" != "Swaptacular Nodes Registry" || \
      "$DN_OU" != "$(cat "$DIR/db/nodetype")" || \
      "$DN_SERIAL_NUMBER" != "$(cat "$DIR/db/nodeid")" ]]; then
    echo
    echo 'ERROR: The subject in the certificate signing request is not the same as'
    echo '       the issuer of your root CA certificate. You are not supposed to'
    echo '       issue server certificates for Swaptacular nodes other than your own.'
    echo
    exit 1
fi

openssl ca \
    -config "$DIR/root-ca.conf" \
    -in "$csr_file" \
    -out "$crt_file" \
    -days "${2-365}" \
    -extensions server_ext

if [ -s "$crt_file" ]; then
    echo
    echo '***********************************************************************'
    echo '* IMPORTANT: A new certificate file has been created. You can use     *'
    echo '*            it to establish secure SSL connections with other        *'
    echo '*            Swaptacular nodes.                                       *'
    echo '***********************************************************************'
    echo "File location: $crt_file"
fi
