apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: The only reason this config-map-generator is added here, is to
# ensure that this kustomization file is valid, even before a peer
# node has been added. When a peer node gets added, this file will be
# automatically overridden by the `create-peer-manifest` script.
#
configMapGenerator:
- name: dummy-configmap
  literals:
  - foo=bar
